### ISSUE TITLE
First event to check if setup alright

### ISSUE THREAD

**Issue by ImaCrea** [thathoff/kirby-sentry#12]
Hi there,
thanks for this plugin ! I just installed, we'll see how it goes ^^

I was wondering if it might be good to send an event at the beginning so one can verify the connection is ok and all is set.

At the moment I don't know how to see if it's actually set up and I don't feel like throwing an error on purpose on a production site.

Thanks again!

**Comment by thathoff** [comment]
Great idea to just have an url or something that you can call to send a test event. Thanks!

In the meantime you could place a template somewhere where you throw an exception in or something like this.

**Comment by ImaCrea** [comment]
> In the meantime you could place a template somewhere where you throw an exception in or something like this.

I'm afraid I'm not sure how to do that ^^' but thanks for your quick answer!

**Comment by thathoff** [comment]
Just add `<?php throw new Exception("This should show up in Sentry"); ?>` to one of your templates. Beware: This will lead to a „This site is offline” error in Kirby so place it in a template that is not used for a live page.

**Comment by ImaCrea** [comment]
I'll try that. Thanks ! :)
